name: Bug Report
description: File a bug report
labels: "Bug"
body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to fill out this bug report! Before
        submitting your issue, make sure this has not been already
        reported or if it works with the latest published version
        of Docker snap.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: >
        If applicable, add screenshots to help explain your
        problem.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: >
        Provide a step-by-step instruction of how to reproduce the behavior.
    validations:
      required: true

  - type: input
    id: revision
    attributes:
      label: Docker snap revision number
      description: >
        Applicable only if installed from the Store.
        Which revision number of the Docker snap are you using?
        You can check this by running `snap list docker` under the `Rev` column.
      placeholder: "123"

  - type: textarea
    id: snapversion
    attributes:
      label: Snapd version
      description: >
        Please paste here the output for the command:
          `snap version`
    validations:
      required: true

  - type: textarea
    id: osrelease
    attributes:
      label: OS version
      description: >
        Please paste here the output for the command:
          `cat /etc/os-release`
          `lsb_release -a`
    validations:
      required: true

  - type: textarea
    id: arch
    attributes:
      label: Architecture
      description: >
        Please paste here the output for the command:
          `uname -orvm`
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: >
        Please copy and paste any relevant log output. This will be
        automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Provide any additional information you may find useful here.
