name: Store Publish

on:
  pull_request:
  push:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # PR_NUMBER: ${{ github.event.pull_request.number }} # TODO: Try this latter
        PR_NUMBER: ${{ github.event.number }}
        RUN: ${{ github.run_number}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        uses: snapcore/action-build@v1
        id: snapcraft

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: hello_test_snap_${{ github.run_number}}
          path: ${{ steps.snapcraft.outputs.snap }}

      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_LOGIN }}
        with:
          snap: ${{ steps.snapcraft.outputs.snap }}
          release: latest/edge/pr-${{ env.RUN }}
