name: reactive-test

on:
  workflow_run:
    workflows: ["trigger"]
    types:
      - completed

jobs:
  check-pr-number:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Save event number
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          echo "PR_NUMBER-> $PR_NUMBER "
