name: trigger

on:
  # pull_request:
  # push:
  workflow_dispatch:

jobs:
  test:
    env:
      PR_NUM: ${{ github.event.pull_request.number }}
      EV_NUM: ${{ github.event.number }}
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: |
          
          echo -e "\n PR number-> $PR_NUM x ${{ env.PR_NUM }} \nEV number-> $EV_NUM x ${{ env.EV_NUM }}\n"

          echo -e "Testing\n"
