name: trigger

on:
  push:
    branches: ["main"]

jobs:
  test:
    env:
      PR: ${{ github.event.pull_request.number }}
      EV: ${{ github.event.number }}
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: |
          
          echo -e "\n PR number-> $PR x ${{ env.PR }} \nEV number-> $EV x ${{ env.EV }}\n"

          echo -e "Testing\n"
